name: Prod CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: List files after checkout
        run: |
          pwd
          ls
      - name: Run build
        id: build
        run: cd "./snowball-fight/"
      - run: npm install
      - run: npm run build
      - name: List files after build
        run: |
          pwd
          ls
      - name: FTP Deploy to https://snowball-fight.com/
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          local-dir: "./snowball-fight/build/"
          server-dir: ./
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USER_NAME}}
          password: ${{secrets.FTP_PASSWORD}}
